### ISSUE TITLE
Some requests

### ISSUE THREAD

**Issue by mercrutio13** [mercrutio13/gvmabstbook#1]
- Change image width
- Possibility to add extra images

**Comment by AdrienAngeAndre** [comment]
Add 2 small issues
-there should be a space after the comma "Day,nb Month Year" in the schedule.
-is it possible to remove the red boxes in the pdf. I think this can be done with a parameter in the package hyperref.

**Comment by mercrutio13** [comment]
The above listed issues have been split into individual issue tickets.
